version: '2'

networks:
  nginx-proxy:
    external: true

services:
  {{PROJECT_NAME}}-nginx:
    build:
      dockerfile: ./.deploy/nginx/Dockerfile
      context: .
    image: {{{REGISTRY_URL}}}/nginx:latest
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST={{VIRTUAL_HOST}}
      - VIRTUAL_PORT=80
      - HEALTH_CHECKER=http
      {{#LETSENCRYPT_HOST}}- LETSENCRYPT_HOST={{LETSENCRYPT_HOST}}{{/LETSENCRYPT_HOST}}
      {{#LETSENCRYPT_EMAIL}}- LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}{{/LETSENCRYPT_EMAIL}}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    volumes_from:
      - {{PROJECT_NAME}}-php
    links:
      - {{PROJECT_NAME}}-php
    depends_on:
      - {{PROJECT_NAME}}-php
    restart: always
  {{PROJECT_NAME}}-php:
    build:
      dockerfile: ./.deploy/php/Dockerfile
      context: .
    image: {{{REGISTRY_URL}}}/php:latest
    restart: always
    ports:
      - 9000
    environment:
      - DRUPAL_VERSION={{DRUPAL_VERSION}}
      - PHP_UPLOAD_MAX_SIZE=256M
      - PHP_POST_MAX_SIZE=256M
    env_file:
      - .env
    volumes:
      - "/docker/{{PROJECT_NAME}}/data/modules:/var/www/html/modules"
      - "/docker/{{PROJECT_NAME}}/data/sites:/var/www/html/sites"
      - "/docker/{{PROJECT_NAME}}/data/themes:/var/www/html/themes"
    networks:
      - nginx-proxy
    external_links:
      - mysql
