# https://github.com/wsargent/docker-cheat-sheet

version: '2.0'

services:
  {{PROJECT_NAME}}:
    container_name: {{PROJECT_NAME}}
    networks:
      - nginx-proxy
    restart: always
    image: postgres:11.1
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD={{DB_PASSWORD}}
    volumes:
      - "/docker/{{PROJECT_NAME}}/data/:/var/lib/postgresql/data"
networks:
  nginx-proxy:
      external: true
