# https://github.com/wsargent/docker-cheat-sheet

version: '2.0'

services:
  postgresql:
    container_name: postgresql
    networks:
      - nginx-proxy
    restart: always
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - "./data/:/var/lib/postgresql/data"
networks:
  nginx-proxy:
      external: true
