# https://github.com/wsargent/docker-cheat-sheet

version: '2'

networks:
  nginx-proxy:
    external: true

services:
  {{PROJECT_NAME}}:
    build:
      dockerfile: ./.deploy/Dockerfile
      context: .
    image: {{REGISTRY_URL}}/{{PROJECT_NAME}}:latest
    restart: always
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST={{VIRTUAL_HOST}}
      - VIRTUAL_PORT={{VIRTUAL_PORT}}
      - HEALTH_CHECKER=http
      - HEALTH_TIMEOUT=5000
