# https://github.com/wsargent/docker-cheat-sheet

version: '2'

services:
  {{PROJECT_NAME}}:
    build:
      dockerfile: ./.deploy/Dockerfile
      context: .
    container_name: {{PROJECT_NAME}}
    image: {{{REGISTRY_URL}}}:latest
    networks:
      - nginx-proxy
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "/docker/{{PROJECT_NAME}}/data:/var/lib/mysql"
    restart: always
    env_file:
      - .env

networks:
  nginx-proxy:
      external: true
