# https://github.com/wsargent/docker-cheat-sheet

version: '2.0'

services:
  {{PROJECT_NAME}}:
    container_name: {{PROJECT_NAME}}
    networks:
      - nginx-proxy
    image: mongo:4.1
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - '/docker/{{PROJECT_NAME}}/data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: {{DB_MONGO_INITDB_ROOT_USERNAME}}
      MONGO_INITDB_ROOT_PASSWORD: {{DB_MONGO_INITDB_ROOT_PASSWORD}}
    restart: always

networks:
  nginx-proxy:
    external: true
