# specify env variables saved in Gitlab
.createEnv: &createEnv |
  echo "GITLAB_DOMAIN=${GITLAB_DOMAIN}" >> .env
  echo "GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}" >> .env

stages:
  - build
  - deploy
build:
  stage: build
  image: docker:latest
  only:
    - "master"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build -f ./.deploy/Dockerfile --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest
  after_script:
    - docker logout $CI_REGISTRY
deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - *createEnv
    - scp -r ./.env ./.deploy ./docker-compose.yml user@${DEPLOYMENT_SERVER_IP}:~/
    - ssh user@$DEPLOYMENT_SERVER_IP "docker stop {{PROJECT_NAME}}; docker rm {{PROJECT_NAME}}; docker login -u $CI_REGISTRY_USER -p ${CI_JOB_TOKEN} $CI_REGISTRY; docker-compose pull; docker-compose -f docker-compose.yml --project-name=$(date +%y%m%d%H%M%S) up -d;"
