# https://github.com/wsargent/docker-cheat-sheet

version: '2.0'

services:
  {{PROJECT_NAME}}:
    container_name: {{PROJECT_NAME}}
    networks:
      - nginx-proxy
    image: adminer:latest
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST={{VIRTUAL_HOST}}
      - VIRTUAL_PORT=8080
      {{#LETSENCRYPT_HOST}}- LETSENCRYPT_HOST={{LETSENCRYPT_HOST}}{{/LETSENCRYPT_HOST}}
      {{#LETSENCRYPT_EMAIL}}- LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}{{/LETSENCRYPT_EMAIL}}
    restart: always
networks:
  nginx-proxy:
      external: true
