# https://github.com/wsargent/docker-cheat-sheet

version: '2'

services:
  {{PROJECT_NAME}}:
    image: 'portainer/portainer:1.19.2'
    container_name: {{PROJECT_NAME}}
    restart: always
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST={{VIRTUAL_HOST}}
      - VIRTUAL_PORT={{VIRTUAL_PORT}}
      {{#LETSENCRYPT_HOST}}- LETSENCRYPT_HOST={{LETSENCRYPT_HOST}}{{/LETSENCRYPT_HOST}}
      {{#LETSENCRYPT_EMAIL}}- LETSENCRYPT_EMAIL={{LETSENCRYPT_EMAIL}}{{/LETSENCRYPT_EMAIL}}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  nginx-proxy:
    external: true
