# https://github.com/wsargent/docker-cheat-sheet

version: '2'

services:
  mysql:
    container_name: mysql
    networks:
      - nginx-proxy
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
      - ./my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
networks:
  nginx-proxy:
      external: true
